### ISSUE TITLE
Hud color

### ISSUE THREAD

**Issue by Rushaway** [darkerz7/EntWatch_DZ#5]
The hud color commands work on others game than CS:GO. For exemple it works on CS:S
https://github.com/darkerz7/EntWatch_DZ/blob/master/addons/sourcemod/scripting/entwatch/module_hud.inc#L604
![image](https://github.com/darkerz7/EntWatch_DZ/assets/11679883/cb7ee0fd-41c2-45f3-84b1-e0c04ed1826d)

**Comment by darkerz7** [comment]
![image](https://github.com/darkerz7/EntWatch_DZ/assets/25752428/5d3cb17c-db0b-40d7-bcbe-a857755980ba)

**Comment by maxime1907** [comment]
I think he meant that if it works on css, why not let the user configure the way he prefers ?

I had `sm_hudtype` in my MR here if you want to take a look at it:
- https://github.com/darkerz7/EntWatch_DZ/pull/2
